springdoc:
  use-management-port: true

app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: liquibase/master.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
  server:
    port: 9090

logging:
  config: classpath:log4j2-plain.xml
