springdoc:
  use-management-port: true

app:
  telegram-token: ${BOT_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
  server:
    port: 8090

logging:
  config: classpath:log4j2-plain.xml
